### ISSUE TITLE
Error: could not find function "testExperimentHubMetadata"

### ISSUE THREAD

**Issue by drighelli** [Bioconductor/HubPub#4]
When creating a new EH package and trying to run `devtoolos::test()` it says:

`Error: could not find function "testExperimentHubMetadata"`

which call is present into the `tests/testthat/test_metadata.R` file.

Indeed, I looked for this function on the Internet, but I wasn't able to find it.

Maybe some internal script or similar?

Thanks!

**Comment by Kayla-Morrell** [comment]
@drighelli - Thank you for reporting this issue. It seems that I'm using an incorrect function for testing. I'll work on getting this fixed.

In the mean time, you can change your EH package test code to use the function `ExperimentHubData::makeExperimentHubMetadata()` instead. This is the correct function for testing the metadata file.

**Comment by drighelli** [comment]
thanks!
